### ISSUE TITLE
Release beta6

### ISSUE THREAD

**Issue by giggio** [aspnet/Scaffolding#105]
It is not published to Nuget.org, for both:
* https://www.nuget.org/packages/Microsoft.Framework.CodeGenerators.Mvc/
* https://www.nuget.org/packages/Microsoft.Framework.CodeGeneration/

The tag is there, but not release:
https://github.com/aspnet/Scaffolding/releases/tag/1.0.0-beta6

**Comment by heathyates** [comment]
I closed my issue at aspnet/Mvc since @giggio created it here in scaffolding. This is creating a lot of problems for users. Including this [issue](https://github.com/aspnet/MusicStore/issues/516)

**Comment by giggio** [comment]
I noticed it has been published to the `aspnetmaster` feed on myget: https://www.myget.org/gallery/aspnetmaster
I added it to my `nuget.config` file and it seems to be working. But I have to do more tests.

**Comment by Eilon** [comment]
@sayedihashimi @danroth27 to confirm but I believe we're pointing people at the Yeoman generators instead of these packages for now. We're not sure what the future is for these packages. That they were tagged as `beta6` is I think just an artifact of our build publishing scripts. We do still build the package and publish to MyGet, but not to NuGet.org anymore.

**Comment by heathyates** [comment]
This resolved the issue for me now as well.

**Comment by Muchiachio** [comment]
I wonder if this is a good idea, especially after [.tt support discussion](https://github.com/aspnet/Home/issues/272).
I can't even start to image how would someone iterate through C# type in yeoman's js.

**Comment by giggio** [comment]
That is the exact problem of using yeoman to run a scaffolding. It is fine to use yeoman to bootstrap the project, but JavaScript cannot work with Roslyn to find types and create the correct files.
The current implementation with Razor is beautiful and works really well. We are creating our own scaffoldings using it. I hope Microsoft won't drop this package/repo. I also hope they keep it up to date with beta7, etc, until 1.0, even if not supported.

**Comment by sayedihashimi** [comment]
>@sayedihashimi @danroth27 to confirm but I believe we're pointing people at the Yeoman generators instead of these packages for now. 

Not exactly, I'll try and clear it up here.

First let's make sure that we are using the same language since "scaffolding" means different things to different people. First let's consider it through the lens of Visual Studio 2013. In VS2013 we have the following ways to add ASP.NET related files.

 - New Project
 - Add New Item
 - Add New Scaffolded Item

The difference between `Add New Item` and `Add New Scaffolded Item` is that the former is just a static text based item template, which at most may contain replacement parameters. Where as `Add New Scaffolded Item` will generate content based on the project artifacts. For example it can generate views/controllers based on an Entity Framework model. So `Add New Scaffolded Item` has to be able to understand the project.

So scaffolding has these two high level definitions.
 - Generate static assets
 - Generate assets based on existing assets

I think yeoman is great at the first part *Generate static assets*. We already have existing [yo generators](https://github.com/OmniSharp/generator-aspnet) which are equivalent to `File->New Project` and `Add New Item` from Visual Studio for ASP.NET 5. For ASP.NET 5 to generate assets based on the project (i.e. views/controllers for an EF Model) will require inspecting the project (i.e. loading the types and understanding them) so it will require DNX support. So having a yeoman only story to generate views/controllers doesn't really make too much sense.

Now back to the question, what are our plans with scaffolding? For scaffolding there are two high level scenarios.
 - Scaffolding in VS
 - Command line scaffolding

The in VS experience has always been a higher priority. When we started looking at the scaffolding experience we were thinking to build an experience inside of VS which was built on top of a command line experience. A few months back we created the command line scaffolding prototype. Since then we have decided that defining a great command line experience for scaffolding would take more time than what we currently have. Our thoughts are to enable an in Visual Studio experience for scaffolding and then at a later time create a cross platform command line experience. The initial support is likely to be based on the UI that we already have for VS2013 and will likely use T4 as the engine to create the content like it was in VS2013.

So to answer the question, what's the future of the CodeGenerator nuget package. Development is pretty much "on hold" for that now. Once we have time we will revisit our command line scaffolding experience and we are not sure what exactly that will entail. We are not likely to even think about this until 1.0 is shipped which is [currently slated for Q1 2016](https://github.com/aspnet/Home/wiki/Roadmap).

If there is enough interest in a command line scaffolding story created by the community let me know. I'd love to be involved in that effort.

**Comment by sayedihashimi** [comment]
@heathyates 
>do you have some updated articles you are aware of for yeoman generators to create the Controllers/Views for an MVC project

Here is the latest on yo aspnet http://blogs.msdn.com/b/webdev/archive/2015/07/04/updates-to-asp-net-5-yeoman-generators-for-beta-5.aspx

@Muchiachio 
>I wonder if this is a good idea, especially after .tt support discussion.
I can't even start to image how would someone iterate through C# type in yeoman's js.

See my reply https://github.com/aspnet/Scaffolding/issues/105#issuecomment-127765528

@giggio 
>That is the exact problem of using yeoman to run a scaffolding. It is fine to use yeoman to bootstrap the project, but JavaScript cannot work with Roslyn to find types and create the correct files.

Yes I agree. See my reply https://github.com/aspnet/Scaffolding/issues/105#issuecomment-127765528.
