### ISSUE TITLE
Checkbox not correct in generated view

### ISSUE THREAD

**Issue by simasch** [aspnet/Scaffolding#166]
When I add a MVC6 controller with views the Checkboxes are wrong:

``` html
<div class="checkbox">
    <input asp-for="HasPlaene" />
    <label asp-for="HasPlaene"></label>
</div>
```

Should be 

``` html
<div class="checkbox">
    <label>
        <input asp-for="HasPlaene" />
        <label asp-for="HasPlaene"></label>
    </label>
</div>
```

**Comment by dougbu** [comment]
@simasch why would it be an improvement to place a `<label>` within a `<label>`?

**Comment by simasch** [comment]
sorry for my short bug report.

Bootstrap requires that the label tag surrounds the input tag:

 <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>

And the only solution I found was to duplicate the label tag.

**Comment by dougbu** [comment]
> Bootstrap requires that the label tag surrounds the input tag

I've seen that in examples but not described as a requirement. What text did I miss?

If a `<label>` is not allowed within another `<label>`, may need to use something like `@Html.DisplayNameFor()` instead of the inner `<label>`. Better actually since you don't need the `for` attribute generated for the inner `<label>`.

Note MVC Core 1 does not yet support generating labels around `<input>` elements; see aspnet/Mvc#2369. But your bare `<label>` should work.

**Comment by simasch** [comment]
The problem with bootstrap is that the label has a padding-left: 20px and the checkbox a margin-left:-20px;

If there is no surrounding label then the checkbox is -20 px on the left wrong aligned.

So i will have to adjust all my checkboxes after scaffolding. Hope this will be fixed in either way in the future.

**Comment by simasch** [comment]
I changed my code to this:

````
 <label>
   <input asp-for="HasPlaene" />@Html.DisplayNameFor(m => m.HasPlaene)
</label>
````
That's was scaffold should generate in my opinion

**Comment by barrytang** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232584&fullScreen=false&_a=edit">232584</a>

**Comment by Eilon** [comment]
Removing from milestone because this milestone already shipped.

**Comment by vijayrkn** [comment]
This is fixed.
