### ISSUE TITLE
extensibility documentation

### ISSUE THREAD

**Issue by jmurphzyo** [aspnet/Scaffolding#394]
I was wondering if any documentation was in the works of how extensibility for this library would work. i.e custom views that aren't cshtml files and so on.

**Comment by prafullbhosale** [comment]
@jmurphzyo, here is a sample custom scaffolder that works with `project.json` based projects
It should serve as a good starting point on how to write custom scaffolders. 
For supporting MsBuild based projects the idea is similar, 
you would need to use the MsBuild version (`1.0.0-msbuild3-final`) of `Microsoft.VisualStudio.Web.CodeGeneration` dependency instead of 
https://github.com/prafullbhosale/CustomScaffolder/blob/master/src/CustomScaffolder/project.json#L8

Let me know if face any issues.
