### ISSUE TITLE
Creating T4 Template in .netcore

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [aspnet/Scaffolding#413]
Hi i am totally lost. How to write a T4 template for .net core. and what will be dependencies and what will be the scaffolding command for this template.
I am doing development in VS2015 Windows.

**Comment by mlorbetske** [comment]
Hi @ali-raza-iftikhar, as mentioned in dotnet/templating#408, this repo is for the scaffolding experience for .NET Core that uses Razor to do the templating (rather than T4) and there is no plan to add support for T4 here. I'd suggest filing an issue on [Connect](https://connect.microsoft.com/), but I'm not aware of any command line tooling for T4 and .NET Core.
