### ISSUE TITLE
Prefer FirstOrDefaultAsync  to SingleOrDefaultAsync

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#649]
The scaffolder generates calls to `FirstOrDefaultAsync `.  Per @ajcvickers [comment here](https://github.com/aspnet/Docs/pull/4451#discussion_r148109121)

It's usually best to use `FirstOrDefaultAsync` unless the code specifically needs to check that there really is no more than one entity returned, because doing that check fetches more data and does more work.

**Comment by Rick-Anderson** [comment]
@ajcvickers given we have the PK, wouldn't it be even better to use `FindAsync(id)` ?

**Comment by ajcvickers** [comment]
@Rick-Anderson There are pros an cons:
* Find is simple and concise if all you need is to look up a single entity.
* Find can have perf benefits in some situations, but they rarely come into play for normal web scenarios.
* Find implicitly does First instead of Single.
* But if you want to Include other entities, then Find is no longer appropriate. This means that you may need to abandon Find and move to a query as your app progresses.

So then the main question is whether or not it is worth increasing the concept count and creating a pivot point in the learning process for the relatively minor benefits in the first three bullet points. If I'm put on the spot, I would say start with query in the first place because the grow up story is better, but I think a strong case could be made either way. /cc @divega

**Comment by Rick-Anderson** [comment]
Closing because `FirstOrDefaultAsync` is appropriate. cc @tdykstra
