### ISSUE TITLE
[Preview2-Validation] Overriding a specific page for a project generated with Authentication enabled causes unnecessary changes to multiple files

### ISSUE THREAD

**Issue by kichalla** [aspnet/Scaffolding#727]
**VS version:**
15.7.Preview 3.0 [27604.0.d15.7]

**Repro:**
- Create 'WebApplication` based project (with git repository enabled so that you can easily see the changes) with `Individual User Accounts` authentication enabled
- Add the following class 
  ```c#
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
  ```
- Right-click on `Areas\Identity` | Add | Identity | Choose to override `Account\Manage\EnableAuthenticator` | choose `ApplicationDbContext` for database context | Add
- This causes changes in multiple files
   - `Pages\Shared\_Layout.cshtml` is changed with incorrect changes and also my this shared folder already has a `_LoginPartial.cshtml`
   - `Area\Identity\Pages\_ViewStart.cshtml` file content is changed to change the layout value from 
`"/Pages/Shared/_Layout.cshtml"` to `"/Pages/Shared/_Layout.chstml"` (notice the file extension change)
   - I was expecting to see only the EnableAuthenticator related files, but not sure why these `ManageNav` files are being generated (I now understand what they are for, but would be good to see if we can write code in a different way so that scaffolder doesn't find the need to generate them)
     ![image](https://user-images.githubusercontent.com/6559784/38391319-c43d432e-38d8-11e8-8b23-7ac9647b3a54.png)
   - Can we reduce the number of `_ViewImports.cshtml` files being generated?
      ![image](https://user-images.githubusercontent.com/6559784/38391466-26c085ec-38d9-11e8-8448-d09b3d2619f3.png)
   - `IdentityHostingStartup.cs` is created whose content is ideally not required as the project was created with authentication enabled. I think the scaffolder is missing/ignoring this context.

**Comment by danroth27** [comment]
@prafullbhosale

**Comment by prafullbhosale** [comment]
cc @seancpeters @vijayrkn

**Comment by seancpeters** [comment]
@kichalla @javiercn @mkArtakMSFT 
I believe this issue is satisfied, at least in the current work scope. The issue calls out 3 things:

_LoginPartial.cshtml created when it shouldn't be. This is dealt with by #748 

_Layout.cshtml was incorrectly called _Layout.chstml. Fixed by #745

The other part is about the creation of ManageNav pages – it mentions that Identity scaffolding shouldn’t need to generate them. Given the current Identity scaffolding content, the ManageNav pages are created iff they’re needed (see TL/DR below). Therefore, we’d need to completely re-work the Identity Scaffolded content to do anything about the ManageNav page generation, which seems far out of scope for the current work.

TL/DR;

Looking through the pages that users can choose to have the Identity scaffolder create, this is what I see:

_ManageNav is referenced by this page, and so if it’s selected for creation, then _ManageNav is needed:
-	Account.Manage._Layout.cshtml
-	Also _ManageNav references ManageNavPages, so if _ManageNav is created, ManageNavPages is needed.

ManageNavPages is referenced by each of these pages, and so if any of them are created, then _ ManageNavPages is needed:
-	Account.Manage.DeletePersonalData.cshtml
-	Account.Manage.Disable2fa.cshtml
-	Account.Manage.DownloadPersonalData.cshtml
-	Account.Manage.EnableAuthenticator.cshtml
-	Account.Manage.GenerateRecoveryCodes.cshtml
-	Account.Manage.PersonalData
-	Account.Manage.ResetAuthenticator.cshtml
-	Account.Manage.SetPassword

No other pages cause _ManageNav or ManageNavPages to be created.

**Comment by kichalla** [comment]
> The other part is about the creation of ManageNav pages – it mentions that Identity scaffolding shouldn’t need to generate them. Given the current Identity scaffolding content, the ManageNav pages are created iff they’re needed (see TL/DR below). Therefore, we’d need to completely re-work the Identity Scaffolded content to do anything about the ManageNav page generation, which seems far out of scope for the current work.

It was just a suggestion and I think it's OK to skip for now.

> _Layout.cshtml was incorrectly called _Layout.chstml. Fixed by #745

Have you tested the scenario in an MVC application? (i.e the layout path should be `/Views/Shared/_Layout.cshtml`). In general we need coverage of using this scaffolding in an MVC app also, so would be good to try there too.

Other than that I am satisfied with what you mentioned. Please check with @javiercn too.

**Comment by javiercn** [comment]
ManageNavPages is already on the default UI library. There's no need to generate a new copy of it.

**Comment by seancpeters** [comment]
@kichalla - for MVC apps, I'm not clear what you'd like to happen with the _Layout.cshtml file. Currently, if the user does not select an existing layout page in the UI, a new one is created. IF the user selects an existing layout page, no new one is created.

Note: the described behavior includes a minor bug fix in VS that causes the layout page selection to be correctly sent to the scaffolder.

**Comment by prafullbhosale** [comment]
> ManageNavPages is already on the default UI library. There's no need to generate a new copy of it.

https://github.com/aspnet/Scaffolding/blob/dev/src/VS.Web.CG.Mvc/Templates/Identity/Pages/Account/Manage/Account.Manage.PersonalData.cshtml#L5

If the ManageNavPages is not generated, the above line fails with compilation errors. 
I assume that is because the `ViewImports` doesn't include the right namespaces in this case, however, if we include the additional namespace and user chooses to generate the `ManageNavPages` file, won't that lead to conflicts?

**Comment by javiercn** [comment]
Why would we give the user the option to generate ManageNavPages at all?

**Comment by prafullbhosale** [comment]
> Why would we give the user the option to generate ManageNavPages at all?

Are you saying this should never be generated? Even when scaffolding full UI?

**Comment by javiercn** [comment]
@seancpeters What was the resolution in here? If this was done or not, can you clarify and close the issue as appropriate?

**Comment by javiercn** [comment]
@seancpeters What's the behavior today? Do we generate one? I'll let @danroth27 know, but I'm closing this for now.

**Comment by seancpeters** [comment]
On the Add Identity dialog, there's an explicit choice for scaffolding `Account\Manage\ManageNav`. When this is chosen, if an existing ManageNav.cshtml exists, in VS, the user is prompted to confirm if they want to overwrite the existing page.

Also, when certain pages are selected to be scaffolded, they cause other pages to be scaffolded. Both
`Account\Manage\_ManageNav.cshtml` and `Account\Manage\ManageNavPages.cs` are also created if any of the following pages are selected to be scaffolded:
- Account\Manage\Layout
- Account\Manage\DeletePersonalData
- Account\Manage\Disable2fa
- Account\Manage\DownloadPersonalData
- Account\Manage\EnableAuthenticator
- Account\Manage\GenerateRecoveryCodes
- Account\Manage\PersonalData
- Account\Manage\ResetAuthenticator
- Account\Manage\SetPassword
When one of the above pages is selected, which mplicitly causes ManageNav.cshtml & ManageNavPages.cs to be created, the user is NOT prompted, and the files are overwritten. I think this behavior should be changed - so that in addition to the pages the user explicitly chooses to scaffold, the ones that are implicitly created should also be candidates for prompting the user about overwriting them.
