### ISSUE TITLE
multiple files fail: dotnet aspnet-codegenerator identity  --files <List of semicolon separated files to scaffold>

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Scaffolding#851]
The following command
`dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files Account.Register;Account.Login;Account.Logout`

Creates `Account.Register` only, and generates the following error:

```
Account.Login : The term 'Account.Login' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:101
+ ... a.ApplicationDbContext --files Account.Register;Account.Login;Account ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Account.Login:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Account.Logout : The term 'Account.Logout' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:115
+ ... cationDbContext --files Account.Register;Account.Login;Account.Logout
+                                                            ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Account.Logout:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

It ignores the 3rd argument. I'm forced to run the command 3 times to create the 3 files.

```
dotnet --version
2.1.401
```

**Comment by seancpeters** [comment]
@Rick-Anderson - The error you're seeing is due to powershell using semicolon as a command separator, whereas dos does not. Since semicolon is the command separator, powershell sees the first command as:
`dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files Account.Register`
...this correctly invokes the aspnet-codegenerator, but with only the first file argument.

Then powershell sees 2 additional, separate commands, namely:
`Account.Login`
`Account.Logout`

And attempts to invoke each or those, but they are not valid powershell commands. Try typing just `Account.Login` at a powershell prompt, and you'll see the same error output as in the original post, up to, but not including `Account.Logout`.

To get around this issue in powershell, one way is to quote the file list:
`dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout"`

Another way I think will work is to escape the semi-colon, which is done with a preceding backtick in powershell. I have very little experience in powershell, so there may be other good ways to do this too.

**Comment by Rick-Anderson** [comment]
@seancpeters  thanks - that works. I'll document that at [Scaffold Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)

Hopefully most folks will be able the trick between the doc's and this closed githHub issue. We'll see if others have problems.
