### ISSUE TITLE
Typo in template: "route." instead of "routes." 

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Scaffolding#863]
_From @dmitry-pavlov on August 30, 2018 9:40_

When you create a default ASP.NET Core Web Application and then add new area with scaffolding it generates "route." instead of "routes."  

_Copied from original issue: aspnet/Templating#718_

**Comment by seancpeters** [comment]
@dmitry-pavlov - Are you seeing "route.MapRoute" instead of "routes.MapRoute" in the ScaffoldingReadMe.txt that gets created when scaffolding, or in another place in the scaffolded content? 

The readme was updated here #747 and the change to "routes" should be seen if using version 2.1.0 or newer of Microsoft.VisualStudio.Web.CodeGeneration.Design

**Comment by dmitry-pavlov** [comment]
@seancpeters correct. I confirm it's been fixed in 2.1.0
