### ISSUE TITLE
Scaffolding an API does not include ProducesResponseType

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Scaffolding#913]
## Steps to reproduce:
Right-click, Add -> Controller... -> API Controller with actions, using Entity Framework

## Expected behavior:
Actions to be decorated using the `ProducesResponseType` attribute.

## Actual behavior:
Actions not decorated using the `ProducesResponseType` attribute.

### Target framework(s):
netcoreapp2.1

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.1.5

**Comment by vijayrkn** [comment]
@ryanbrandenburg - Does the template match the above? This will help us understand if it is just a scaffolding change.

**Comment by ryanbrandenburg** [comment]
The [controller in the WebApi template](https://github.com/aspnet/Templating/blob/release/2.1/src/Microsoft.DotNet.Web.ProjectTemplates/content/WebApi-CSharp/Controllers/ValuesController.cs) does not decorate actions with `ProducesResponseType`, if that's what you mean.

**Comment by vijayrkn** [comment]
If that is the case, then I dont see any reason for Scaffolding to add this first. 

@danroth27 - Is this something that needs to happen?

**Comment by vijayrkn** [comment]
@vanillajonathan - We try to keep the contents scaffolded by VS as close as possible to the templates so that the users get the same behavior from default templates and from scaffolded templates. It would be good to raise this request in aspnet/templates first and if it gets added, then we can make the same change to scaffolded templates as well. Thanks for taking the time to raise this feature request.

**Comment by vijayrkn** [comment]
Thanks @vanillajonathan. I am closing this issue here. The Templating issue can track changing the templates in both scaffolding and templating.
